run:
  skip-dirs:
    - tests

linters:
  enable:
    - cyclop
    - depguard
    - dupl
    - gocognit
    - gocritic
    - gofmt
    - gosec
    - revive
    - unconvert
    - unparam
    - wrapcheck
  fast: false

linters-settings:
  wrapcheck:
    ignoreSigs:
      - .ErrorOrNil(
      - .Errorf(
